glogal:
  message: Welcome to customer service dev environment!
server:
  port: 8082
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:postgresql://shop_db:5432/customer_master
    username: root
    password: lead4dead
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: false
