glogal:
  message: Welcome to customer service prod environment!
server:
  port: 8083
message: Hello from Prod!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    username: root
    password: lead4dead
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: false
