server:
  port: 8089

logging:
  level:
    root: INFO

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8087/realms/microservices-realm

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
