glogal:
  message: Welcome to user service dev environment!
server:
  port: 8082
message: Hello from Dev!
spring:
  datasource:
    url: jdbc:postgresql://shop_db:5432/user_master
    username: yurguen
    password: 123456789
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: false
